# Week 2 Day Lab

### Problem 1: Installing NumPy

If not already installed, install the numpy library using `!pip install numpy`. After installing, import numpy with variable name `np`.

In [4]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels


In [5]:
import numpy as np

### Problem 2: Installing other libraries
We will use other libraries throughout this semester as well. Here are a couple:

    - matplotlib
    - networkx
    - pandas
    - geopandas
Try importing these libraries. If they are not installed, use `pip install` to install them for future use.

In [6]:
!pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels


In [7]:
!pip install networkx

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels


In [8]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels


In [9]:
!pip install geopandas

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels


In [10]:
#checking the libraries import correctly
import matplotlib
import networkx
import pandas
import geopandas

### Problem 3

Given

```python
a = np.array([2, 4, 6, 8])
```

compute each of the following:

1. a + 3
2. 2 * a
3. a**2
4. a - 1

Do not use a `for` loop.


In [11]:
a = np.array([2, 4, 6, 8])
print(a+3)
print(2*a)
print(a**2)
print(a-1)

[ 5  7  9 11]
[ 4  8 12 16]
[ 4 16 36 64]
[1 3 5 7]


### Problem 4

The derivative of a function \(f(x)\) at a point \(x\) is defined as the limit

$
f'(x)=\lim_{h\to0}\frac{f(x+h)-f(x)}{h}
$

provided the limit exists.

Define a function $g(h)$ that computes the quotient above for a given function $f$ near a point $x$. Then, vectorize $g$. 


Using `np.linspace()`, let $f(x)=sin(x)$ and compute $g$ at $10^{-1}, 10^{-2}, 10^{-3}, 10^{-4}$. This will be an estimate for the derivative of $f$. Compare to the actual derivative.

In [12]:
import math

In [13]:
x = np.pi # some point x

def g(h):                  
    return (f(x+h)-f(x))/h  # quotient for derivative

G = np.vectorize(g)   # vectorize g
def f(x):
    return math.sin(x) # f of choice

h = np.linspace(-1, -4, 4)   # -1, -2, -3, -4
h = 10**h                   # 10^-1, 10^-2, 10^-3, 10^-4

print(G(h))                 # evalutate the vectorized version of g at h values
print(math.cos(np.pi))      # actual derivative

[-0.99833417 -0.99998333 -0.99999983 -1.        ]
-1.0


###  Problem 5
Let

$
A=
\begin{bmatrix}
2 & 1 \\
3 & 4
\end{bmatrix},
\qquad
B=
\begin{bmatrix}
5 & 2 \\
1 & 6
\end{bmatrix}
$

Compute the product.

In [14]:
a = [2,1,3,4]
b = [5,2,1,6]
A = np.array(a).reshape(2,2)
B = np.array(b).reshape(2,2)

In [15]:
A @ B

array([[11, 10],
       [19, 30]])